global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: nginx-exporter
    static_configs:
      - targets:
          - nginx-exporter:9113

  - job_name: gateway-health-probe
    metrics_path: /probe
    params:
      module: [http_health]
    static_configs:
      - targets:
          - http://gateway/nginx_status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - target_label: probe_type
        replacement: gateway-health

  - job_name: checkout-probe
    metrics_path: /probe
    params:
      module: [checkout_probe]
    static_configs:
      - targets:
          - http://gateway/api/v1/checkout/preview
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - target_label: probe_type
        replacement: checkout
